### ISSUE TITLE
No rule to make target 'NetLogo.jar

### ISSUE THREAD

**Issue by zufanka** [aesmaeili/vectorview#1]
I can't seem to build the extension. Where is the problem?

$ make
make: **\* No rule to make target 'NetLogo.jar', needed by 'vectorview.jar'.  Stop.

**Comment by aesmaeili** [comment]
The problem is with the directory you are building the extension. It should simply include `NetLogo.jar` file together with the needed libraries. The easiest solution is to copy the files and directories listed below to the root directory where your NetLogo installation files are present (the directory where `NetLogo.jar` file is). Then `cd` to that directory in your terminal and run `make` .

`src/` directory
`manifest.txt`
`Makefile`
`VectorGraphics2D-0.9.3`

There is also a generated `vectorview.jar` file in `releases` folder that you can use in your projects, without rebuilding the source.
